# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'akuz~' 
tagline:          'machine learning hacker'
description:      'another machine learning hacker''s homepage, wow'
url:              http://akuz.me
baseurl:          /

author:
  name:           'Andrey Kuzmenko'
  url:            https://twitter.com/akuz_me

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/akuz
