# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false
plugins:            [jekyll-paginate]

# Setup
title:               akuz.me/nko
tagline:             "machine learning, artificial intelligence, and what not"
description:         "Another machine learning hacker's homepage &nbsp;<i class='fa fa-cube'></i>"
url:                 http://akuz.me
baseurl:             ""
paginate:            10

# About/contact
author:
  name:              Andrey Kuzmenko
  email:             for.akuz@gmail.com
